inherit_from: ./configs/Dynamic/Wild_SLAM_Mocap/wild_slam_mocap.yaml
scene: ANYmal1

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/scene2/ANYmal1

cam: 
  fx: 647.7445068359375
  fy: 646.9425659179688